version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
    overwrite: yes

permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/beforeRunning.sh
      runas: ec2-user # ec2-user 권한으로 실행.
  AfterInstall:
    - location: scripts/afterRunning.sh
      timeout: 300 # 제한 시간 1000초 으로 설정. 1000초가 넘어가면 실패함.
      runas: ec2-user # ec2-user 권한으로 실행.